version: "2"

services:
    app:
        build: ./docker/app
        depends_on:
            - mysql
        volumes:
            - .:/www

    mysql:
        image: mariadb

    mailcatcher:
        image: schickling/mailcatcher

    tools:
        build: ./docker/tools
        depends_on:
            - mysql
        volumes_from:
            - app

    pma:
        image: phpmyadmin/phpmyadmin
