imports:
    - { resource: config.yml }
    - { resource: services/sentry.xml }

services:
    app.doctrine_redis_cache:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments:
            - "@cache.app"

doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: app.doctrine_redis_cache
        query_cache_driver:
            type: service
            id: app.doctrine_redis_cache

monolog:
    handlers:
        main:
            type:                   fingers_crossed
            action_level:           error
            activation_strategy:    app.logging.activation_strategy
            handler:                nested
        nested:
            type:                   group
            members:                [file, buffer]
        file:
            type:                   stream
            path:                   "%kernel.logs_dir%/%kernel.environment%.log"
        buffer:
            type:                   buffer
            handler:                sentry
        sentry:
            type:                   service
            id:                     app.logging.sentry_handler

        console:
            type:                   console
