imports:
    - { resource: config_dev.yml }

services:
    app.recaptcha.api_client:
        class: AppBundle\Recaptcha\DummyRecaptchaApiClient
        public: false

    app.mailjet.transport:
        class: 'AppBundle\Mailjet\Transport\MailjetNullTransport'
        arguments: ['@?logger']
        public: false

    app.cloudflare.tag_invalidator:
        class: 'AppBundle\Cloudflare\CloudflareNullTagInvalidator'
        arguments: ['@?logger']
        public: false

parameters:
    env(PAYBOX_SITE): "1999888"
    env(PAYBOX_RANK): "32"
    env(PAYBOX_IDENTIFIER): "107904482"
    env(PAYBOX_KEY): "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF"
    adherent_interests:
        agriculture: Agriculture
        culture: Culture
        economie: Économie
        education: Éducation
        emploi: Emploi
        environement: Environement
        europe: Europe
        international: International
        institution: Institution
        jeunesse: Jeunesse
        justice: Justice
        logement: Logement
        numerique: Numérique
        sante: Santé
        securite: Sécurité
        territoire: Territoire

liip_functional_test:
    cache_sqlite_db: true

doctrine:
    dbal:
        driver:      pdo_sqlite
        charset:     UTF8
        path:        "%kernel.root_dir%/../var/cache/test/data.db"

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false
