imports:
    - { resource: config_dev.yml }

services:
    app.recaptcha.api_client:
        class: 'AppBundle\Recaptcha\DummyRecaptchaApiClient'
        public: false

    app.geocoder:
        class: 'AppBundle\Geocoder\DummyGeocoder'
        public: false

    app.glide.cache_adapter:
        class: 'League\Flysystem\Memory\MemoryAdapter'

parameters:
    env(PAYBOX_SITE): "1999888"
    env(PAYBOX_RANK): "32"
    env(PAYBOX_IDENTIFIER): "107904482"
    env(PAYBOX_KEY): "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF"
    adherent_interests:
        agriculture: Agriculture
        culture: Culture
        economie: Économie
        education: Éducation
        emploi: Emploi
        environement: Environement
        europe: Europe
        international: International
        institution: Institution
        jeunesse: Jeunesse
        justice: Justice
        logement: Logement
        numerique: Numérique
        sante: Santé
        securite: Sécurité
        territoire: Territoire

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: 'en_marche_session_%kernel.environment%'
    profiler:
        collect: false
    cache:
        app: cache.adapter.null

web_profiler:
    toolbar: false
    intercept_redirects: false
