lexik_paybox:
    resource: "@LexikPayboxBundle/Resources/config/routing.yml"
    prefix:   "/don"

admin_dashboard:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   "/admin"

admin_crud:
    resource: .
    type:     sonata_admin
    prefix:   "/admin"

app:
    resource: "@AppBundle/Controller/"
    type:     "annotation"

app_admin:
    resource: "@AppBundle/Controller/Admin"
    type:     "annotation"
    prefix:   "/admin"
