security:

    encoders:
        AppBundle\Entity\Adherent: bcrypt

    role_hierarchy:
        ROLE_WRITER:
            - ROLE_ADHERENT
            - ROLE_APP_ADMIN_MEDIA_ALL
            - ROLE_APP_ADMIN_ARTICLE_ALL
            - ROLE_APP_ADMIN_LIVE_LINK_ALL
            - ROLE_APP_ADMIN_HOME_BLOCK_LIST
            - ROLE_APP_ADMIN_HOME_BLOCK_EDIT

        ROLE_ADMIN:
            - ROLE_WRITER
            - ROLE_APP_ADMIN_HOME_BLOCK_ALL

    access_decision_manager:
        strategy: unanimous

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users_db:
            entity: { class: 'AppBundle\Entity\Adherent' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # No pattern means every path is behind this firewall
            anonymous:
                secret: '%env(SECRET)%'
            form_login:
                login_path: app_adherent_login
                check_path: app_adherent_login_check

                default_target_path: events_index
                always_use_default_target_path: true

                username_parameter: _adherent_email
                password_parameter: _adherent_password
                csrf_parameter: _adherent_csrf
                csrf_token_id: authenticate_adherent
            logout:
                path: app_adherent_logout
                target: homepage


    access_control:
        - { path: '^/espace-adherent/mon-profil', roles: [ROLE_ADHERENT] }
        - { path: '^/admin', roles: [ROLE_WRITER] }
